name: ${project.name}
version: ${project.version}
main: org.cyberpwn.vortex.Wormholes
depend: [ProtocolLib]
commands: 
  wormhole: 
    aliases: [w, worm, whole, wormh, wormholes, portal, portals, wh]