name: ${project.name}
version: ${project.version}
main: com.volmit.wormholes.Wormholes
description: Wormholes is a portal plugin which allows servers to show the other side of the portal while looking through them. Blocks and entities will show up as they are on the other side.
depend: [ProtocolLib]
author: Volmit Software
commands: 
  wormhole: 
    aliases: [w, worm, whole, wormh, wormholes, portal, portals, wh]