name: ${project.name}
version: ${project.version}
main: com.volmit.wormholes.Wormholes
depend: [ProtocolLib]
author: Volmit Software
commands: 
  wormhole: 
    aliases: [w, worm, whole, wormh, wormholes, portal, portals, wh]